GET http://localhost:3003/

###

GET http://localhost:3003/accounts

###
GET http://localhost:3003/accounts/client
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiOTExNDI4YzAtY2E4ZS00ZTZkLTlhMGUtYzZkZWRkNzI1NjM2IiwiaWF0IjoxNzE2ODgxNjI5LCJleHAiOjE3MTY4ODM0Mjl9.d_ZQrh4hdh3k3kCpQCdDbBZUBIt7T4DRi2_PT5W7VIwj
###
POST http://localhost:3003/accounts/create
Content-Type: application/json

{
  "name": "Visitante",
  "cpf": "12345678911",
  "email": "visitante@email.com",
  "password": "123456",
  "passwordConf": "123456",
  "initialDate": "1933-03-26"
}

###
#POST https://fakebank-server.vercel.app/accounts/login
POST http://localhost:3003/accounts/login
Content-Type: application/json

{
  "email": "visitante@email.com",
  "password": "123456"
}

###
POST https://fakebank-server.vercel.app/accounts/balance
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiMTc4NDU3YTItMThkNy00NmE4LWFmODAtMDViN2QwM2RlNGVjIiwiaWF0IjoxNjkxOTMxOTkwLCJleHAiOjE2OTE5MzM3OTB9.e_Y-6ed6F8K0U-bg6Qhpp54SIc7LO3kCbRI3F47NAWs

{
  "cpf": "12345678913",
  "password": "123456"
}

###
POST http://localhost:3003/accounts/statement
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiMTc4NDU3YTItMThkNy00NmE4LWFmODAtMDViN2QwM2RlNGVjIiwiaWF0IjoxNjkxODgzNDU2LCJleHAiOjE2OTE4ODUyNTZ9.j66Ms1RHglT5FsJcJG_2GDM6kekLFmtFmYquolcfECw
Content-Type: application/json

{
  "cpf": 12345678913,
  "password": "123456"
}

###
POST http://localhost:3003/accounts/payment
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiMTc4NDU3YTItMThkNy00NmE4LWFmODAtMDViN2QwM2RlNGVjIiwiaWF0IjoxNjkxODg1NDQ1LCJleHAiOjE2OTE4ODcyNDV9.6UJoN0WCfGmn00EsiXGUbdyx46eeKbpdO70wqxkltA4
Content-Type: application/json

{
  "cpf": "12345678913",
  "password": "123456",
  "initialDate": "10/12/2023",
  "value": 127,
  "description": "pagamento de prestação de cartão de crédito"
}

###
POST http://localhost:3003/accounts/deposit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiMTc4NDU3YTItMThkNy00NmE4LWFmODAtMDViN2QwM2RlNGVjIiwiaWF0IjoxNjkxODg3MTA3LCJleHAiOjE2OTE4ODg5MDd9.Lf79pwMxF0zPWAXSIXHkt4MMbu5GfMVhxPIttcycy9w
Content-Type: application/json

{
  "cpf": "12345678913",
  "password": "123456",
  "value": 85
}

###
POST http://localhost:3003/accounts/transfer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiMTc4NDU3YTItMThkNy00NmE4LWFmODAtMDViN2QwM2RlNGVjIiwiaWF0IjoxNjkxODkyNTY3LCJleHAiOjE2OTE4OTQzNjd9.gwt9KZ8j0RROt8H6meJV2YQoNjg-VIlX_x8br6bbLuk
Content-Type: application/json

{
  "cpf": 12345678913,
  "password":"123456",
  "recipientName": "Visitante2",
  "recipientCpf": 12345678911,
  "value": 20
}
